id: 1a51dd08b1224840a8e3d540dea7284d
initial_creation_type: ebook
created_at: 8/04/2021
last_modified_at: 25/11/2021
source_metadata:
  title: test
  subtitle: ''
  authors:
  - test
  collection: ''
  publisher: ''
  id: test
  cover: tmpvtj_ewtt.jpg
  credit: tmpp3ime3f6.jpg
